    [build]
      publish = "."
      command = "echo 'Netlify build complete!'"

    [functions]
      directory = "functions"
      runtime = "python3.9" # Adicione esta linha!

    [[redirects]]
      from = "/api/*"
      to = "/.netlify/functions/api/:splat"
      status = 200
      force = true

    [[redirects]]
      from = "/projects"
      to = "/.netlify/functions/api/projects"
      status = 200
      force = true

    [[redirects]]
      from = "/projects/:id"
      to = "/.netlify/functions/api/projects/:id"
      status = 200
      force = true

    [[redirects]]
      from = "/portfolio"
      to = "/.netlify/functions/api/portfolio"
      status = 200
      force = true

    [[redirects]]
      from = "/portfolio/:id"
      to = "/.netlify/functions/api/portfolio/:id"
      status = 200
      force = true

    [[redirects]]
      from = "/login"
      to = "/.netlify/functions/api/login"
      status = 200
      force = true

    [[redirects]]
      from = "/change-password"
      to = "/.netlify/functions/api/change-password"
      status = 200
      force = true

    [[redirects]]
      from = "/social-links"
      to = "/.netlify/functions/api/social-links"
      status = 200
      force = true
    