[build]
  publish = "."
  command = "echo 'Netlify build complete!'" # Ou seu comando de build do frontend, se houver

[functions]
  directory = "functions"

# Regra de redirecionamento para a função API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# ADICIONE ESTAS REGRAS ABAIXO PARA CAPTURAR AS CHAMADAS DIRETAS
[[redirects]]
  from = "/projects"
  to = "/.netlify/functions/api/projects"
  status = 200
  force = true

[[redirects]]
  from = "/projects/:id"
  to = "/.netlify/functions/api/projects/:id"
  status = 200
  force = true

[[redirects]]
  from = "/portfolio"
  to = "/.netlify/functions/api/portfolio"
  status = 200
  force = true

[[redirects]]
  from = "/portfolio/:id"
  to = "/.netlify/functions/api/portfolio/:id"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "/.netlify/functions/api/login"
  status = 200
  force = true

[[redirects]]
  from = "/change-password"
  to = "/.netlify/functions/api/change-password"
  status = 200
  force = true

[[redirects]]
  from = "/social-links"
  to = "/.netlify/functions/api/social-links"
  status = 200
  force = true

[[redirects]]
  from = "/testimonials"
  to = "/.netlify/functions/api/testimonials"
  status = 200
  force = true

[[redirects]]
  from = "/testimonials/all"
  to = "/.netlify/functions/api/testimonials/all"
  status = 200
  force = true

[[redirects]]
  from = "/testimonials/:id"
  to = "/.netlify/functions/api/testimonials/:id"
  status = 200
  force = true

[[redirects]]
  from = "/testimonials/:id/approve"
  to = "/.netlify/functions/api/testimonials/:id/approve"
  status = 200
  force = true

[[redirects]]
  from = "/spotify-tracks"
  to = "/.netlify/functions/api/spotify-tracks"
  status = 200
  force = true

[[redirects]]
  from = "/spotify-tracks/:id"
  to = "/.netlify/functions/api/spotify-tracks/:id"
  status = 200
  force = true

[[redirects]]
  from = "/blog-posts"
  to = "/.netlify/functions/api/blog-posts"
  status = 200
  force = true

[[redirects]]
  from = "/blog-posts/all"
  to = "/.netlify/functions/api/blog-posts/all"
  status = 200
  force = true

[[redirects]]
  from = "/blog-posts/:id"
  to = "/.netlify/functions/api/blog-posts/:id"
  status = 200
  force = true

[[redirects]]
  from = "/downloadable-items"
  to = "/.netlify/functions/api/downloadable-items"
  status = 200
  force = true

[[redirects]]
  from = "/downloadable-items/:id"
  to = "/.netlify/functions/api/downloadable-items/:id"
  status = 200
  force = true

[[redirects]]
  from = "/studio-config"
  to = "/.netlify/functions/api/studio-config"
  status = 200
  force = true

# --- INÍCIO: NOVOS CABEÇALHOS CORS GLOBAIS (Específicos para seu domínio) ---
[[headers]]
  for = "/*" # Aplica a todos os caminhos
  [headers.values]
    Access-Control-Allow-Origin = "https://cbrecords.online" # AGORA ESPECÍFICO!
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Max-Age = "86400" # Cache de preflight por 24 horas
# --- FIM: NOVOS CABEÇALHOS CORS GLOBAIS ---
