[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/portfolio/:id"
  to = "/.netlify/functions/api/portfolio/:id"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "/.netlify/functions/api/login"
  status = 200
  force = true

[[redirects]]
  from = "/change-password"
  to = "/.netlify/functions/api/change-password"
  status = 200
  force = true
