[build]
  command = "echo 'Netlify build complete!'"
  functions = "functions"  # Indica que suas funções estão no diretório 'functions'
  publish = "."            # O diretório que será publicado (raiz do seu projeto, onde está index.html)

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat" # Redireciona /api para sua função lambda
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200